version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_nginx
    depends_on:
        - label-studio
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  label-studio:
    image: label-studio               # image name (from Dockerfile)
    container_name: label-studio    # container name
    build:
      context: ./web_servers/label_studio       # directory of Dockerfile
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - LABEL_STUDIO_HOST=https://iguana-touched-repeatedly.ngrok-free.app/labelstudio/
    ports:
      - 8081:8080
    restart: on-failure

  photoprism:
    container_name: photoprism
    extends:
      file: ./web_servers/photoprism/docker-compose.yml
      service: photoprism
    depends_on:
      - mariadb

  mariadb:
    extends:
      file: ./web_servers/photoprism/docker-compose.yml
      service: mariadb

  # # generates weather reports
  # weather-report:
  #   image: weather-report
  #   container_name: weather-report
  #   build:
  #     context: ./weather_report
  #   depends_on:
  #       - temperature-service
  #       - precip-service
  #   ports:
  #     - 8080:80
  #   restart: on-failure


  # # Retrieves the temperature
  # temperature-service:
  #   image: temperature-service
  #   container_name: temperature-service
  #   build:
  #     context: ./temperature_service
  #   ports:
  #     - 5001:5001
  #   restart: on-failure


  # # Generates a precipitation estimate
  # precip-service:
  #   image: precip-service
  #   container_name: precip-service
  #   build:
  #     context: ./precip_service
  #   ports:
  #     - 5002:5002
  #   restart: on-failure